### PR TITLE
added additional challenges and messier data

### PR DESCRIPTION
**Pull request by JasonGodloveDuet**
Added additional challenges and an answer sheet here:
https://docs.google.com/document/d/104ZmKEss9GJKlQm3rynT6MQ5V2958gtF0A4Naamales/edit?usp=sharing

### CODE REVIEW

**Comment by duetcharlotte** [comment]
The intentional data errors is a good way to trip people up, but I worry that a small minority of people will catch them

**Comment by JasonGodloveDuet** [comment]
> The intentional data errors is a good way to trip people up, but I worry that a small minority of people will catch them without further clues

I selected providers & organizations that were in the top 5 of most encounters, so it's large enough to get noticed and make a difference. Additionally, I would hope that the applicant will actually look at the results of their new variable to verify it is working and if you sort by highest frequency, those 0 & null errors pop right to the top.

**Comment by duetcharlotte** [comment]
@JasonGodloveDuet Gotcha! That would be good context to include in the answer key doc then

**Comment by duetcharlotte** [comment]
Is this PR publicly viewable to anyone who visits this repo?

**Review by katieclaiborne-duet — APPROVED** [review]
> Is this PR publicly viewable to anyone who visits this repo?

It is indeed. :/ Jason and I have exchanged Slack messages, but let's continue the discussion in the team channel.

We'll likely want to make this repository private, and copy the updated challenge to a new public repository with settings that prevent candidates from opening pull requests.

The updates to the challenge itself look good to me! Thanks for tackling this, Jason.

**Pull request merged**
